[book]
title = "Rosella"
description = "Genome recovery by partitioning a contig neighbour graph"
authors = ["Rhys J. P. Newell"]
src = "docs"
language = "en"

[output.html]
site-url = "/rosella/"
git-repository-url = "https://github.com/rhysnewell/rosella"
edit-url-template = "https://github.com/rhysnewell/rosella/edit/main/{path}"
