use clap::*;
use clap_complete::*;

pub mod help;

pub use help::{recover_full_help, refine_full_help};

pub(crate) const MAPPING_SOFTWARE_LIST: &[&str] = &[
    "bwa-mem",
    "bwa-mem2",
    "minimap2-sr",
    "minimap2-ont",
    "minimap2-pb",
    "minimap2-hifi",
    "minimap2-no-preset",
];


pub(crate) const DEFAULT_MAPPING_SOFTWARE: &str = "minimap2-sr";

pub(crate) const LONGREAD_MAPPING_SOFTWARE_LIST: &[&str] = &["minimap2-ont", "minimap2-pb", "minimap2-hifi"];
pub(crate) const DEFAULT_LONGREAD_MAPPING_SOFTWARE: &str = "minimap2-ont";

// // See https://github.com/rust-cli/roff-rs/issues/19
// fn bold(s: &str) -> String {
//     Roff::new().text([roff_bold(s)]).to_roff()
// }

pub fn build_cli() -> Command {
    Command::new("rosella")
        .version(crate_version!())
        .author(crate::AUTHOR_AND_EMAIL)
        .about(
            &format!(
                "Recover MAGs from contigs using UMAP and HDBSCAN clustering. (version {})",
                crate_version!()
            )
        )
        .arg_required_else_help(true)
        .subcommand(
            Command::new("recover")
                .about("Recover MAGs from contigs using UMAP and HDBSCAN clustering.")
                .arg_required_else_help(true)
                .arg(
                    Arg::new("full-help")
                        .short('H')
                        .long("full-help")
                        .required(false)
                        .action(ArgAction::SetTrue)
                )
                .arg(
                    Arg::new("full-help-roff")
                        .long("full-help-roff")
                        .required(false)
                        .action(ArgAction::SetTrue)
                )
                .arg(
                    Arg::new("assembly")
                        .short('r')
                        .long("assembly")
                        .alias("reference")
                        .required_unless_present_any(&[
                            "full-help",
                            "full-help-roff",
                        ])
                )
                .arg(
                    Arg::new("output-directory")
                        .short('o')
                        .long("output-directory")
                        .required_unless_present_any(&[
                            "full-help",
                            "full-help-roff",
                        ])
                )
                .arg(
                    Arg::new("read1")
                        .short('1')
                        .long("read1")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .requires("read2")
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "single",
                            "coupled",
                            "interleaved",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("read2")
                        .short('2')
                        .long("read2")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .requires("read1")
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "single",
                            "coupled",
                            "interleaved",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("coupled")
                        .short('c')
                        .long("coupled")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "interleaved",
                            "single",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("interleaved")
                        .long("interleaved")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "single",
                            "interleaved",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("single")
                        .long("single")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "interleaved",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("longreads")
                        .long("longreads")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "interleaved",
                            "single",
                            "full-help", "full-help-roff",
                            "longread-bam-files"
                        ]),
                )
                .arg(
                    Arg::new(
                        "bam-files"
                    )
                    .short('b').long("bam-files")
                    .action(ArgAction::Append)
                    .num_args(1..)
                    .required_unless_present_any(&[
                        "coverage-file",
                        "read1",
                        "coupled",
                        "interleaved",
                        "single",
                        "full-help", "full-help-roff",
                        "longreads",
                        "longread-bam-files"
                    ]),
                )
                .arg(
                    Arg::new("longread-bam-files")
                        .short('l').long("longread-bam-files")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "interleaved",
                            "single",
                            "full-help", "full-help-roff",
                            "longreads",
                        ]),
                )
                .arg(
                    Arg::new("threads")
                        .short('t').long("threads")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("10"),
                )
                .arg(
                    Arg::new("mapper")
                        .short('p')
                        .long("mapper")
                        .value_parser(MAPPING_SOFTWARE_LIST.iter().collect::<Vec<_>>())
                        .default_value(DEFAULT_MAPPING_SOFTWARE),
                )
                .arg(
                    Arg::new("longread-mapper")
                        .long("longread-mapper")
                        .value_parser(LONGREAD_MAPPING_SOFTWARE_LIST.iter().collect::<Vec<_>>())
                        .default_value(DEFAULT_LONGREAD_MAPPING_SOFTWARE),
                )
                .arg(
                    Arg::new("minimap2-params")
                        .long("minimap2-params")
                        .long("minimap2-parameters")
                        .allow_hyphen_values(true),
                )
                .arg(
                    Arg::new("minimap2-reference-is-index")
                        .long("minimap2-reference-is-index"),
                )
                .arg(
                    Arg::new("bwa-params")
                        .long("bwa-params")
                        .long("bwa-parameters")
                        .allow_hyphen_values(true),
                ).arg(
                    Arg::new("min-read-aligned-length")
                        .long("min-read-aligned-length")
                        .value_parser(clap::value_parser!(u32)),
                )
                .arg(
                    Arg::new("min-read-percent-identity")
                        .long("min-read-percent-identity")
                        .value_parser(clap::value_parser!(f32)),
                )
                .arg(
                    Arg::new("min-read-aligned-percent")
                        .long("min-read-aligned-percent")
                        .value_parser(clap::value_parser!(f32))
                        .default_value("0.0"),
                )
                .arg(
                    Arg::new("min-read-aligned-length-pair")
                        .long("min-read-aligned-length-pair")
                        .value_parser(clap::value_parser!(u32)),
                )
                .arg(
                    Arg::new("min-read-percent-identity-pair")
                        .long("min-read-percent-identity-pair")
                        .value_parser(clap::value_parser!(f32)),
                )
                .arg(
                    Arg::new("min-read-aligned-percent-pair")
                        .long("min-read-aligned-percent-pair")
                        .value_parser(clap::value_parser!(f32)),
                )
                .arg(
                    Arg::new("min-covered-fraction")
                        .long("min-covered-fraction")
                        .value_parser(clap::value_parser!(f32))
                        .default_value("0.0"),
                )
                .arg(
                    Arg::new("proper-pairs-only")
                        .long("proper-pairs-only")
                        .action(clap::ArgAction::SetTrue)
                )
                .arg(Arg::new("include-secondary").long("include-secondary").action(clap::ArgAction::SetTrue))
                .arg(Arg::new("exclude-supplementary").long("exclude-supplementary").action(clap::ArgAction::SetTrue))
                .arg(
                    Arg::new("contig-end-exclusion")
                        .long("contig-end-exclusion")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("75"),
                )
                .arg(
                    Arg::new("trim-min")
                        .long("trim-min")
                        .value_parser(clap::value_parser!(f32))
                        .default_value("5.0"),
                )
                .arg(
                    Arg::new("trim-max")
                        .long("trim-max")
                        .value_parser(clap::value_parser!(f32))
                        .default_value("95.0"),
                )
                .arg(
                    Arg::new("coverage-file")
                        .long("coverage-file")
                        .short('C')
                        .value_parser(clap::value_parser!(String))
                        .required_unless_present_any(
                            // conflics with all read and BAM options
                            &[
                                "read1",
                                "read2",
                                "coupled",
                                "interleaved",
                                "single",
                                "longreads",
                                "longread-bam-files",
                                "bam-files",
                                "full-help",
                                "full-help-roff",
                            ]
                        )
                )
                .arg(
                    Arg::new("seed")
                        .long("seed")
                        .value_parser(clap::value_parser!(u64))
                        .default_value("42"),
                )
                .arg(
                    Arg::new("kmer-frequency-file")
                        .long("kmer-frequency-file")
                        .short('K')
                        .value_parser(clap::value_parser!(String))
                )
                .arg(
                    Arg::new("min-contig-size")
                        .long("min-contig-size")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("1500"),
                )
                .arg(
                    Arg::new("min-bin-size")
                        .long("min-bin-size")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("200000"),
                )
                .arg(
                    Arg::new("max-bin-size")
                        .long("max-bin-size")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("15000000"),
                )
                .arg(
                    Arg::new("min-contig-count")
                        .long("min-contig-count")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("10"),
                )
                .arg(
                    Arg::new("n-neighbours")
                        .long("n-neighbours")
                        .alias("n-neighbors")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("100"),
                )
                .arg(
                    Arg::new("max-retries")
                        .long("max-retries")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("5"),
                )
                .arg(
                    Arg::new("refine")
                        .long("refine")
                        .action(ArgAction::SetTrue),
                )
                .arg(
                    Arg::new("verbose")
                        .short('v')
                        .long("verbose")
                        .action(ArgAction::SetTrue),
                )
                .arg(
                    Arg::new("quiet")
                        .short('q')
                        .long("quiet")
                        .action(ArgAction::SetTrue),
                )
        )
        .subcommand(
            Command::new("refine")
                .about("Refine MAGs using UMAP and HDBSCAN clustering.")
                .arg_required_else_help(true)
                .arg(
                    Arg::new("full-help")
                        .short('H')
                        .long("full-help")
                        .required(false)
                        .action(ArgAction::SetTrue)
                )
                .arg(
                    Arg::new("full-help-roff")
                        .long("full-help-roff")
                        .required(false)
                        .action(ArgAction::SetTrue)
                )
                .arg(
                    Arg::new("assembly")
                        .short('r')
                        .long("assembly")
                        .alias("reference")
                        .required_unless_present_any(&[
                            "full-help",
                            "full-help-roff",
                        ])
                        .required_unless_present_all(&[
                            "coverage-file",
                            "kmer-frequency-file",
                        ])
                )
                .arg(
                    Arg::new("output-directory")
                        .short('o')
                        .long("output-directory")
                        .required_unless_present_any(&[
                            "full-help",
                            "full-help-roff",
                        ])
                )
                .arg(
                    Arg::new("genome-fasta-files")
                        .short('f')
                        .long("genome-fasta-files")
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "full-help",
                            "full-help-roff",
                            "genome-fasta-directory"
                        ])
                )
                .arg(
                    Arg::new("genome-fasta-directory")
                        .short('d')
                        .long("genome-fasta-directory")
                        .required_unless_present_any(&[
                            "full-help",
                            "full-help-roff",
                            "genome-fasta-files"
                        ])
                )
                .arg(
                    Arg::new("genome-fasta-extension")
                        .short('x')
                        .long("genome-fasta-extension")
                        .default_value("fna")
                )
                .arg(
                    Arg::new("checkm-results")
                        .long("checkm-results")
                        .required(false)
                )
                .arg(
                    Arg::new("threads")
                        .short('t').long("threads")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("10"),
                )
                .arg(
                    Arg::new("read1")
                        .short('1')
                        .long("read1")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .requires("read2")
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "single",
                            "coupled",
                            "interleaved",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("read2")
                        .short('2')
                        .long("read2")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .requires("read1")
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "single",
                            "coupled",
                            "interleaved",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("coupled")
                        .short('c')
                        .long("coupled")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "interleaved",
                            "single",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("interleaved")
                        .long("interleaved")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "single",
                            "interleaved",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("single")
                        .long("single")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "interleaved",
                            "longreads",
                            "longread-bam-files",
                            "full-help",
                            "full-help-roff",
                        ]),
                )
                .arg(
                    Arg::new("longreads")
                        .long("longreads")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "interleaved",
                            "single",
                            "full-help", "full-help-roff",
                            "longread-bam-files"
                        ]),
                )
                .arg(
                    Arg::new(
                        "bam-files"
                    )
                    .short('b').long("bam-files")
                    .action(ArgAction::Append)
                    .num_args(1..)
                    .required_unless_present_any(&[
                        "coverage-file",
                        "read1",
                        "coupled",
                        "interleaved",
                        "single",
                        "full-help", "full-help-roff",
                        "longreads",
                        "longread-bam-files"
                    ]),
                )
                .arg(
                    Arg::new("longread-bam-files")
                        .short('l').long("longread-bam-files")
                        .action(ArgAction::Append)
                        .num_args(1..)
                        .required_unless_present_any(&[
                            "coverage-file",
                            "bam-files",
                            "read1",
                            "coupled",
                            "interleaved",
                            "single",
                            "full-help", "full-help-roff",
                            "longreads",
                        ]),
                )
                .arg(
                    Arg::new("mapper")
                        .short('p')
                        .long("mapper")
                        .value_parser(MAPPING_SOFTWARE_LIST.iter().collect::<Vec<_>>())
                        .default_value(DEFAULT_MAPPING_SOFTWARE),
                )
                .arg(
                    Arg::new("longread-mapper")
                        .long("longread-mapper")
                        .value_parser(LONGREAD_MAPPING_SOFTWARE_LIST.iter().collect::<Vec<_>>())
                        .default_value(DEFAULT_LONGREAD_MAPPING_SOFTWARE),
                )
                .arg(
                    Arg::new("minimap2-params")
                        .long("minimap2-params")
                        .long("minimap2-parameters")
                        .allow_hyphen_values(true),
                )
                .arg(
                    Arg::new("minimap2-reference-is-index")
                        .long("minimap2-reference-is-index"),
                )
                .arg(
                    Arg::new("bwa-params")
                        .long("bwa-params")
                        .long("bwa-parameters")
                        .allow_hyphen_values(true),
                ).arg(
                    Arg::new("min-read-aligned-length")
                        .long("min-read-aligned-length")
                        .value_parser(clap::value_parser!(u32)),
                )
                .arg(
                    Arg::new("min-read-percent-identity")
                        .long("min-read-percent-identity")
                        .value_parser(clap::value_parser!(f32)),
                )
                .arg(
                    Arg::new("min-read-aligned-percent")
                        .long("min-read-aligned-percent")
                        .value_parser(clap::value_parser!(f32))
                        .default_value("0.0"),
                )
                .arg(
                    Arg::new("min-read-aligned-length-pair")
                        .long("min-read-aligned-length-pair")
                        .value_parser(clap::value_parser!(u32))
                )
                .arg(
                    Arg::new("min-read-percent-identity-pair")
                        .long("min-read-percent-identity-pair")
                        .value_parser(clap::value_parser!(f32))
                )
                .arg(
                    Arg::new("min-read-aligned-percent-pair")
                        .long("min-read-aligned-percent-pair")
                        .value_parser(clap::value_parser!(f32))
                )
                .arg(
                    Arg::new("proper-pairs-only")
                        .long("proper-pairs-only")
                        .action(clap::ArgAction::SetTrue)
                )
                .arg(Arg::new("include-secondary").long("include-secondary")
                    .action(clap::ArgAction::SetTrue))
                .arg(Arg::new("exclude-supplementary").long("exclude-supplementary").action(clap::ArgAction::SetTrue))
                .arg(
                    Arg::new("contig-end-exclusion")
                        .long("contig-end-exclusion")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("75"),
                )
                .arg(
                    Arg::new("trim-min")
                        .long("trim-min")
                        .value_parser(clap::value_parser!(f32))
                        .default_value("5.0"),
                )
                .arg(
                    Arg::new("trim-max")
                        .long("trim-max")
                        .value_parser(clap::value_parser!(f32))
                        .default_value("95.0"),
                )
                .arg(
                    Arg::new("min-covered-fraction")
                        .long("min-covered-fraction")
                        .value_parser(clap::value_parser!(f32))
                        .default_value("0.0"),
                )
                .arg(
                    Arg::new("coverage-file")
                        .long("coverage-file")
                        .short('C')
                        .value_parser(clap::value_parser!(String))
                        .required_unless_present_any(&[
                            "read1",
                            "read2",
                            "coupled",
                            "interleaved",
                            "single",
                            "longreads",
                            "longread-bam-files",
                            "bam-files",
                            "full-help",
                            "full-help-roff"
                        ])
                )
                .arg(
                    Arg::new("seed")
                        .long("seed")
                        .value_parser(clap::value_parser!(u64))
                        .default_value("42"),
                )
                .arg(
                    Arg::new("kmer-frequency-file")
                        .long("kmer-frequency-file")
                        .short('K')
                        .value_parser(clap::value_parser!(String))
                        .required(false)
                )
                .arg(
                    Arg::new("min-contig-size")
                        .long("min-contig-size")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("1500"),
                )
                .arg(
                    Arg::new("min-bin-size")
                        .long("min-bin-size")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("200000"),
                )
                .arg(
                    Arg::new("max-bin-size")
                        .long("max-bin-size")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("15000000"),
                )
                .arg(
                    Arg::new("min-contig-count")
                        .long("min-contig-count")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("10"),
                )
                .arg(
                    Arg::new("n-neighbours")
                        .long("n-neighbours")
                        .alias("n-neighbors")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("100"),
                )
                .arg(
                    Arg::new("max-contamination")
                        .long("max-contamination")
                        .value_parser(clap::value_parser!(f64))
                        .default_value("15.0"),
                )
                .arg(
                    Arg::new("max-retries")
                        .long("max-retries")
                        .value_parser(clap::value_parser!(usize))
                        .default_value("5"),
                )
                .arg(
                    Arg::new("bin-tag")
                        .long("bin-tag")
                        .value_parser(clap::value_parser!(String))
                        .default_value("refined_1")
                )
                .arg(
                    Arg::new("verbose")
                        .short('v')
                        .long("verbose")
                        .action(ArgAction::SetTrue),
                )
                .arg(
                    Arg::new("quiet")
                        .short('q')
                        .long("quiet")
                        .action(ArgAction::SetTrue),
                )
        )
        .subcommand(
            Command::new("shell-completion")
                .about("Generate a shell completion script for lorikeet")
                .arg(
                    Arg::new("output-file")
                        .short('o')
                        .long("output-file")
                        .required(true),
                )
                .arg(
                    Arg::new("shell")
                        .long("shell")
                        .required(true)
                        .value_parser(value_parser!(Shell)),
                )      
                .arg(
                    Arg::new("verbose")
                        .short('v')
                        .long("verbose")
                        .action(ArgAction::SetTrue),
                )
                .arg(
                    Arg::new("quiet")
                        .short('q')
                        .long("quiet")
                        .action(ArgAction::SetTrue),
                ),
        )
}